plugins {
    id "com.android.application"
}

android {
    namespace "com.paladin173.microbes"
    compileSdk 37

    defaultConfig {
        applicationId "com.paladin173.microbes"
        minSdk 23
        targetSdk 37
        versionCode 20
        versionName "0.6.4"
    }
}

dependencies {
    testImplementation "junit:junit:4.13.2"
}
